name: ACR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/cn/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login
      run: |
        docker login --username=${{ secrets.ALIYUN_USERNAME }} \
          ${{ vars.ALIYUN_REGISTRY }} \
          --password=${{ secrets.ALIYUN_PASSWORD }}

    - name: Build
      working-directory: ./website/cn
      run: |
        docker compose --progress=plain build --no-cache

        docker tag ${{ vars.ALIYUN_PROJECT_NAME }}:latest \
          ${{ vars.ALIYUN_REGISTRY }}:latest

        docker push ${{ vars.ALIYUN_REGISTRY }}:latest

