name: ACR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/cn/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login
      run: |
        docker login --username=${{ secrets.ALIYUN_USERNAME }} \
          ${{ vars.ALIYUN_REGISTRY }} \
          --password=${{ secrets.ALIYUN_PASSWORD }}

    - name: Build
      working-directory: ./website/cn
      run: |
        docker system prune -f

        docker compose build

        LATEST_IMAGE_ID=$(docker images --format "{{.ID}} {{.CreatedAt}}" | sort -rk2 | head -1 | awk '{print $1}')

        if [ -z "$LATEST_IMAGE_ID" ]; then
          exit 1
        fi

        docker tag $LATEST_IMAGE_ID \
          ${{ vars.ALIYUN_REGISTRY }}/candleview/candleview-website-cn:latest

        docker push ${{ vars.ALIYUN_REGISTRY }}/candleview/candleview-website-cn:latest
