name: ACR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/cn/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login
      run: |
        docker login --username=${{ secrets.ALIYUN_USERNAME }} \
          ${{ vars.ALIYUN_REGISTRY }} \
          --password=${{ secrets.ALIYUN_PASSWORD }}

    - name: Build
      working-directory: ./website/cn
      run: |
        docker compose build

        SERVICE_NAME=$(docker compose config --services | head -1)

        DIR_NAME=$(basename $(pwd))

        IMAGE_NAME="${DIR_NAME}_${SERVICE_NAME}:latest"

        docker tag $IMAGE_NAME \
          ${{ vars.ALIYUN_REGISTRY }}/candleview/candleview-website-cn:latest

        docker push ${{ vars.ALIYUN_REGISTRY }}/candleview/candleview-website-cn:latest
